{% set name = "yt-napari" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yt_napari-{{ version }}.tar.gz
  sha256: bebcc5e05ebadaa77166f86eecf8eadf546b60395b363902ffbb6b524002dde5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - magicgui >=0.4.0
    - napari >=0.4.13
    - npe2
    - numpy
    - pydantic
    - python >=3.7
    - yt >=4.0.1

test:
  imports:
    - yt_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/data-exp-lab/yt-napari
  summary: A napari plugin for loading data from yt
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrishavlin
    - goanpeca
    - jaimergp
