{% set name = "yt-napari" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yt_napari-{{ version }}.tar.gz
  sha256: 8289c52622afa30e8a38d4900d050040d2162aef167086ae566cd7b3441010c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui >=0.4.0
    - napari >=0.4.13
    # - npe2  # Declared but not used
    - numpy
    - packaging
    - pydantic
    - python >=3.8
    - qtpy
    - unyt
    - yt >=4.0.1

test:
  imports:
    - yt_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/yt-napari
  summary: A napari plugin for loading data from yt
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/data-exp-lab/yt-napari

extra:
  recipe-maintainers:
    - chrishavlin
    - goanpeca
    - jaimergp
